### ISSUE TITLE
What is meant by 'Minecraft Libraries'

### ISSUE THREAD

**Issue by AdminDeveloper** [Wurst-Imperium/Wurst-MC-1.8#2429]
In step 5 of the ReadMe it says to place the 'Minecraft libraries' in the folder named lib but I am not sure what is meant by Minecraft Libraries. Thank you.

**Comment by Alexander01998** [comment]
"Minecraft's libraries" means all libraries used by Minecraft, like GSON, AuthLib, etc. The MCP will give you those libraries, you just need to move them all into the "lib" folder.

**Comment by AdminDeveloper** [comment]
Thank you. Great work on wurst by the way. 😄
