### ISSUE TITLE
how do i use .setmode

### ISSUE THREAD

**Issue by TERMINATOR309** [Wurst-Imperium/Wurst-MC-1.8#2436]
when ever i type . setmode it says i am doing it wrong and it must be done .setmode <feature> <mode_setting> (<mode>:next:prev) but when ever i fill it out it tells me _______ is not a feature
please help

**Comment by TERMINATOR309** [comment]
can you make it so u can use all the commands in any gamemode not just creative

**Comment by TekkitCommando** [comment]
@TERMINATOR309 ... Obviously that wouldn't work.
