### ISSUE TITLE
Crash on initial startup.

### ISSUE THREAD

**Issue by LoudSoftware** [Wurst-Imperium/Wurst-MC-1.8#2437]
Cannot start the client at all, am getting:

```
Completely ignored arguments: [--nativeLauncherVersion, 307]
[12:47:25] [Client thread/INFO]: Setting user: LoudSoftware
[12:47:25] [Client thread/INFO]: (Session ID is <censored>)
[12:47:26] [Client thread/INFO]: LWJGL Version: 2.9.1
```

When trying to launch it.

**Comment by Twijn** [comment]
Same thing happening to me. There is another tab where it shows the launcher log (I think) where it says "Ignoring visibility rule and showing launcher due to a game crash". No crash log is made anywhere and it does not give any specifics.
